/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2025-09-29 01:37:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import DB.DBConnect;
import java.sql.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DB.DBConnect");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- db파일 받아오기 -->\r\n");
      out.write("\r\n");
      out.write("<!-- sql 관련 java의 library 받기 -->\r\n");

String sql = "select max(custno) from member_tbl_02"; //sql이라는 문자열 변수에 쓸 쿼리문 저장
//구문 저장
Connection conn = DBConnect.getConnection(); //Db 연결 기능을 conn 변수에 저장, 이후 db 연결
// db와 연결을 위해 객체 생성
PreparedStatement pstmt = conn.prepareStatement(sql);//변수 sql에 저장된 문장을 쿼리로 변경, db 연결 후 실행
//연결용 객체를 통해 구문 실행, 이를 다른 객체에 저장, 그 객체는 구문을 저장
//여기서 sql이 구문이 됨
ResultSet rs = pstmt.executeQuery();//변수 pstmt에 있는 쿼리문을 실행 후 rs에 저장
//그 구문을 실행하여 그 결과물을 저장
//결과를 저장하는 데이터타입, 책과 같은 형식?	
rs.next(); //rs에 있는 결과를 next()로 호출, 마지막 값 저장
//next()는 정보의 가장 마지막 부분을 확인할 수 있음

int num = rs.getInt(1) +1; //num에 뽑은 결과(member 테이블 속 마지막 회원번호)에 +1해서 값 저장
//이 num을 join하려는 사람에게 적용

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원 가입 관리</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css\\style.css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function checkValue(){\r\n");
      out.write("\tif(!document.data.custname.value){\r\n");
      out.write("\t\t//document 객체(웹페이지),data(폼 이름),(custname = input의 name)\r\n");
      out.write("\t\tdata.custname.focus();\r\n");
      out.write("\t\talert(\"회원 이름 비설정됨\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}else if(!document.data.phone.value){\r\n");
      out.write("\t\tdata.phone.focus();\r\n");
      out.write("\t\talert(\"회원 전화번호 비설정됨\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(!document.data.address.value){\r\n");
      out.write("\t\tdata.address.focus();\r\n");
      out.write("\t\talert(\"회원 주소 비설정됨\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(!document.data.joindate.value){\r\n");
      out.write("\t\tdata.joindate.focus();\r\n");
      out.write("\t\talert(\"회원 가입일자 비설정됨\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(!document.data.grade.value){\r\n");
      out.write("\t\tdata.grade.focus();\r\n");
      out.write("\t\talert(\"회원 등급 비설정됨\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(!document.data.city.value){\r\n");
      out.write("\t\tdata.city.focus();\r\n");
      out.write("\t\talert(\"회원 등급 비설정됨\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"fin\");\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Layout\\header.jsp", out, false);
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("<nav>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Layout\\nav.jsp", out, false);
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("<section class=\"section\">\r\n");
      out.write("\r\n");
      out.write("<h2>sushi1 join</h2>\r\n");
      out.write("<form name=\"data\" action=\"join_p.jsp\" method=\"post\" onsubmit=\"return checkValue()\">\r\n");
      out.write("<table class=\"table_line\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th>\r\n");
      out.write("회원번호(자동발생)\r\n");
      out.write("</th>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"custno\" value=\"");
      out.print( num );
      out.write("\" readonly>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>\r\n");
      out.write("회원성명\r\n");
      out.write("</th>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"custname\" value=\"\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>\r\n");
      out.write("회원전화\r\n");
      out.write("</th>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"phone\" value=\"\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>\r\n");
      out.write("회원주소\r\n");
      out.write("</th>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"address\" value=\"\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>\r\n");
      out.write("가입일자\r\n");
      out.write("</th>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"joindate\" value=\"\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>\r\n");
      out.write("고객등급(A:vip,B:일반,C:직원)\r\n");
      out.write("</th>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"grade\" value=\"\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>\r\n");
      out.write("도시코드\r\n");
      out.write("</th>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"city\" value=\"\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td colspan=\"2\">\r\n");
      out.write("<input type=\"submit\" value=\"등록\">\r\n");
      out.write("<input type=\"button\" value=\"취소\" onclick=\"location.href='join.jsp'\">\r\n");
      out.write("<input type=\"button\" value=\"조회\" onclick=\"location.href='member_list.jsp'\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</section>\r\n");
      out.write("<footer>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Layout\\footer.jsp", out, false);
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
