/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2025-09-19 01:14:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import DB.DBConnect;
import java.sql.*;

public final class member_005fsearch_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DB.DBConnect");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

//- **조회하고 있는** 회원번호 (request.getParameter 이용, 형변환 필요, 변수에저장)
int in_custno = Integer.parseInt(request.getParameter("in_custno"));
// - 회원번호가 저장 된 변수를 회원정보 조회 쿼리문에 이용 (where custno = 변수)
String sql="select custno, custname, phone, address, "
+ "to_char(joindate,'yyyy-mm-dd') joindate,"
+ "case when grade = 'A' then 'VIP' when grade = 'B' then '일반' else '직원' end grade,"
+ "city from member_tbl_02 where custno=" + in_custno;
Connection conn = DBConnect.getConnection();
PreparedStatement pstmt = conn.prepareStatement(sql);
ResultSet rs = pstmt.executeQuery();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<title>회원정보조회 결과</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Layout\\header.jsp", out, false);
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("<nav>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Layout\\nav.jsp", out, false);
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("<section class=\"section\">\r\n");
      out.write("<h2>회원 조회 결과</h2><br>\r\n");

if(rs.next()){ 
      out.write(" <!-- //DB에 해당 회원이 있는 경우....테이블에 정보들이 출력,\r\n");
      out.write("member_list와 동일 형식 -->\r\n");
      out.write("<table class=\"table_line\">\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<th>회원번호</th>\r\n");
      out.write("<th>회원성명</th>\r\n");
      out.write("<th>회원전화</th>\r\n");
      out.write("<th>회원주소</th>\r\n");
      out.write("<th>가입일자</th>\r\n");
      out.write("<th>고객등급[A:VIP,B:일반,C:직원]</th>\r\n");
      out.write("<th>도시코드</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("<td>");
      out.print( rs.getString("custno") );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print( rs.getString("custname") );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<td>");
      out.print( rs.getString("phone") );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print( rs.getString("address") );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print( rs.getString("joindate") );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print( rs.getString("grade") );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print( rs.getString("city") );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("<td colspan=\"7\" align=\"center\">\r\n");
      out.write("<input type=\"button\" value=\"홈으로\"\r\n");
      out.write("\r\n");
      out.write("onclick=\"location.href='index.jsp'\">\r\n");
      out.write("</td></tr></table>\r\n");
      out.write("\r\n");
} else{ 
      out.write(" <!-- 회원번호가 없는 경우 메시지를 출력 -->\r\n");
      out.write("<p align=\"center\">회원번호 ");
      out.print( in_custno );
      out.write("의 회원 정보가 없습니다.</p>\r\n");
      out.write("<p align=\"center\"> <input type=\"button\" value=\"다시조회\"\r\n");
      out.write("onclick=\"location.href='member_search.jsp'\"></p>\r\n");
 } 
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<footer>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Layout\\footer.jsp", out, false);
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
